Repository airweave-ai/airweave, pull requests merged in 2025-03, with the labels that each got.

#11 Enhancement: POSTGRES_SERVER to POSTGRES_HOST in each file.
  .env.example
  .gitignore
  backend/app/core/config.py
  backend/entrypoint.sh
  fern/docs/pages/concepts.mdx
  fern/docs/pages/welcome.mdx
Labels: enhancement

#15 feat: implement MCP server + cursorrules for automated source generation
  .cursor/mcp/sync_test/README.md
  .cursor/mcp/sync_test/server.py
  .cursor/rules/backend-rules.mdc
  .cursor/rules/integrations-yaml.mdc
  .cursor/rules/source-integration-rules.mdc
  backend/app/api/v1/api.py
  backend/app/api/v1/endpoints/cursor_dev.py
  backend/app/core/config.py
  backend/app/crud/crud_connection.py
  backend/app/main.py
  backend/poetry.lock
  backend/pyproject.toml
Labels: enhancement

#17 test: set up framework
  .cursor/rules/airweave-overview.mdc
  .cursor/rules/backend-rules.mdc
  .github/workflows/tests.yml
  .gitignore
  .vscode/launch.json
  .vscode/settings.json
  README.md
  backend/.coveragerc
  backend/Dockerfile.dev
  backend/entrypoint.dev.sh
  backend/pyproject.toml
  backend/pytest.ini
  backend/tests/README.md
  backend/tests/__init__.py
  backend/tests/conftest.py
  backend/tests/docker/docker-compose.test.yml
  backend/tests/e2e/README.md
  backend/tests/e2e/__init__.py
  backend/tests/e2e/conftest.py
  backend/tests/e2e/runner.py
  backend/tests/e2e/scenarios/__init__.py
  backend/tests/e2e/scenarios/test_source_connection.py
  backend/tests/e2e/scenarios/test_sync_operations.py
  backend/tests/e2e/smoke/__init__.py
  backend/tests/e2e/smoke/test_basic_health.py
  backend/tests/helpers/__init__.py
  backend/tests/helpers/docker.py
  backend/tests/helpers/llm_judge.py
  backend/tests/integration/__init__.py
  backend/tests/integration/api/__init__.py
  backend/tests/integration/crud/__init__.py
  backend/tests/integration/crud/test_source_integration.py
  backend/tests/unit/__init__.py
  backend/tests/unit/api/__init__.py
  backend/tests/unit/api/test_api_keys.py
  backend/tests/unit/api/test_health.py
  backend/tests/unit/api/test_users.py
  backend/tests/unit/crud/__init__.py
  backend/tests/unit/crud/test_source.py
  backend/tests/unit/platform/__init__.py
Labels: enhancement

#22 fix(models): rename schema column in entity_definition
  backend/airweave/models/entity_definition.py
  backend/airweave/platform/db_sync.py
  backend/airweave/schemas/entity_definition.py
  backend/alembic/versions/456789abcdef_rename_schema_column.py
Labels: bug

#40 feat: labels for source and destination integrations
  backend/airweave/models/destination.py
  backend/airweave/models/source.py
  backend/airweave/platform/db_sync.py
  backend/airweave/platform/decorators.py
  backend/airweave/platform/destinations/_base.py
  backend/airweave/platform/destinations/neo4j.py
  backend/airweave/platform/destinations/weaviate.py
  backend/airweave/platform/destinations/weaviate_native.py
  backend/airweave/platform/sources/_base.py
  backend/airweave/platform/sources/asana.py
  backend/airweave/platform/sources/confluence.py
  backend/airweave/platform/sources/dropbox.py
  backend/airweave/platform/sources/github.py
  backend/airweave/platform/sources/gmail.py
  backend/airweave/platform/sources/google_calendar.py
  backend/airweave/platform/sources/google_drive.py
  backend/airweave/platform/sources/hubspot.py
  backend/airweave/platform/sources/intercom.py
  backend/airweave/platform/sources/jira.py
  backend/airweave/platform/sources/monday.py
  backend/airweave/platform/sources/mysql.py
  backend/airweave/platform/sources/notion.py
  backend/airweave/platform/sources/onedrive.py
  backend/airweave/platform/sources/oracle.py
  backend/airweave/platform/sources/outlook_calendar.py
  backend/airweave/platform/sources/outlook_mail.py
  backend/airweave/platform/sources/postgresql.py
  backend/airweave/platform/sources/slack.py
  backend/airweave/platform/sources/sql_server.py
  backend/airweave/platform/sources/sqlite.py
  backend/airweave/platform/sources/todoist.py
  backend/airweave/platform/sources/trello.py
  backend/airweave/platform/sources/zendesk.py
  backend/airweave/schemas/destination.py
  backend/airweave/schemas/source.py
  backend/alembic/versions/1ab50fcb59fb_add_labels.py
Labels: enhancement

#20 Add codespell support (config, workflow to detect/not fix) and make it fix few typos
  .codespellrc
  .cursor/rules/backend-rules.mdc
  .cursor/rules/integrations-yaml.mdc
  .github/workflows/codespell.yml
  .pre-commit-config.yaml
  CONTRIBUTING.md
  README.md
  fern/docs/pages/concepts.mdx
Labels: documentation, enhancement

#47 feat: live sync screen
  backend/airweave/crud/crud_sync.py
  frontend/src/components/sync/SyncProgress.tsx
  frontend/src/pages/SyncCreate.tsx
  frontend/src/pages/ViewEditSync.tsx
  frontend/src/pages/sync-progress.css
Labels: enhancement
