Repository airweave-ai/airweave, pull requests merged in 2025-04, with the labels that each got.

#50 feat: polish ui
  backend/airweave/api/v1/api.py
  backend/airweave/api/v1/endpoints/connections.py
  backend/airweave/api/v1/endpoints/search.py
  backend/airweave/api/v1/endpoints/white_label.py
  backend/airweave/core/chat_service.py
  backend/airweave/models/sync.py
  backend/airweave/models/white_label.py
  backend/airweave/platform/scheduler.py
  fern/README.md
  fern/definition/overrides.yml
  fern/docs/pages/architecture.mdx
  fern/docs/pages/extending-connectors.mdx
  fern/docs/pages/setup.mdx
  fern/generate-local.sh
  frontend/src/components/DestinationSelector.tsx
  frontend/src/components/chat/ApiReferenceDialog.tsx
  frontend/src/components/chat/ChatInfoSidebar.tsx
  frontend/src/components/chat/ChatInput.tsx
  frontend/src/components/chat/ChatMessage.tsx
  frontend/src/components/chat/ChatSidebar.tsx
  frontend/src/components/chat/types.ts
  frontend/src/components/icons/McpIcon.tsx
  frontend/src/components/icons/NodeIcon.tsx
  frontend/src/components/icons/PythonIcon.tsx
  frontend/src/components/icons/destinations/neo4j.png
  frontend/src/components/icons/destinations/neo4j_native.png
  frontend/src/components/sync/SyncJobsTable.tsx
  frontend/src/components/sync/SyncProgress.tsx
  frontend/src/components/sync/nodes/DestinationNode.tsx
  frontend/src/components/ui/code-block.tsx
  frontend/src/components/ui/data-table.tsx
  frontend/src/components/white-label/CodeSnippet.tsx
  frontend/src/components/white-label/TestIntegrationCard.tsx
  frontend/src/index.css
  frontend/src/pages/Chat.tsx
  frontend/src/pages/CreateWhiteLabel.tsx
  frontend/src/pages/SyncCreate.tsx
  frontend/src/pages/SyncTableView.tsx
  frontend/src/pages/ViewEditWhiteLabel.tsx
  frontend/src/pages/WhiteLabel.tsx
  frontend/src/pages/sync-progress.css
Labels: enhancement

#45 feat(sources): ClickUp as data source Integration
  backend/airweave/platform/auth/yaml/dev.integrations.yaml
  backend/airweave/platform/auth/yaml/prod.integrations.yaml
  backend/airweave/platform/entities/clickup.py
  backend/airweave/platform/sources/clickup.py
  frontend/src/components/icons/apps/clickup-light.svg
  frontend/src/components/icons/apps/clickup.svg
  frontend/src/lib/utils/icons.ts
Labels: enhancement, integration

#49 fix: confluence integration, sync job updates and saving edited dags
  backend/airweave/api/v1/endpoints/dag.py
  backend/airweave/crud/crud_dag.py
  backend/airweave/crud/crud_sync_job.py
  backend/airweave/platform/entities/confluence.py
  backend/airweave/platform/sources/confluence.py
  backend/airweave/platform/sync/context.py
  backend/airweave/platform/sync/orchestrator.py
  backend/airweave/platform/sync/pubsub.py
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/sync/SyncDagEditor.tsx
  frontend/src/components/sync/dag.ts
Labels: bug, enhancement

#55 feat(platform)!: swap weaviate for qdrant
  .env.example
  .gitignore
  .pre-commit-config.yaml
  .vscode/launch.json
  backend/airweave/api/v1/endpoints/connections.py
  backend/airweave/core/chat_service.py
  backend/airweave/core/config.py
  backend/airweave/core/constants/native_connections.py
  backend/airweave/core/search_service.py
  backend/airweave/crud/crud_connection.py
  backend/airweave/crud/crud_sync_job.py
  backend/airweave/db/init_db_native.py
  backend/airweave/platform/auth/yaml/dev.integrations.yaml
  backend/airweave/platform/auth/yaml/prod.integrations.yaml
  backend/airweave/platform/configs/auth.py
  backend/airweave/platform/destinations/_base.py
  backend/airweave/platform/destinations/neo4j.py
  backend/airweave/platform/destinations/qdrant.py
  backend/airweave/platform/destinations/qdrant_native.py
  backend/airweave/platform/destinations/weaviate.py
  backend/airweave/platform/embedding_models/_base.py
  backend/airweave/platform/embedding_models/local_text2vec.py
  backend/airweave/platform/embedding_models/openai_text2vec.py
  backend/airweave/platform/entities/_base.py
  backend/airweave/platform/sources/asana.py
  backend/airweave/platform/sync/context.py
  backend/airweave/platform/sync/orchestrator.py
  backend/airweave/platform/sync/pubsub.py
  backend/airweave/platform/sync/service.py
  backend/airweave/vector_db/weaviate_service.py
  backend/poetry.lock
  backend/pyproject.toml
  backend/tests/docker/docker-compose.test.yml
  backend/tests/e2e/conftest.py
  backend/tests/e2e/smoke/test_basic_health.py
  backend/tests/helpers/docker.py
  backend/tests/platform/__init__.py
  backend/tests/platform/embedding_models/__init__.py
  backend/tests/platform/embedding_models/conftest.py
  backend/tests/platform/embedding_models/test_local_text2vec.py
  backend/tests/platform/embedding_models/test_openai_text2vec.py
  backend/tests/unit/platform/test_qdrant_destination.py
  docker-compose.dev.yml
  docker-compose.yml
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/sync/SyncProgress.tsx
  frontend/src/constants/nativeConnections.ts
  frontend/src/pages/SyncCreate.tsx
Labels: enhancement
